stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  image: ruby:2.4.2
  variables:
    DATABASE_URL: 'mongodb://mongo/user_posts'
  services:
    - mongo:latest
  before_script:
    - cd reddit
    - bundle install
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_job:
  stage: deploy
  script:
    - echo 'Deploy'
